Rickroll no ads- Harmless
hak5/usbrubberducky-payloads pull request #146
Opened 2022-09-17 19:43 UTC by J0K3RS-L4UGH

A rickroll no ads

2022-09-17 21:39 UTC, Concara3443 requested changes
Can be shorter

2022-09-17 21:41 UTC, Concara3443 requested changes

2022-09-17 21:41 UTC, Concara3443 commented on payloads/library/prank/AllOperatingSystemRickroll/all
> +DELAY 2000
```suggestion
GUI r
```

2022-09-18 08:44 UTC, J0K3RS-L4UGH commented
> Can be shorter

How?

2022-09-18 08:47 UTC, J0K3RS-L4UGH commented
This is made to work in all operating systems, including ChromeOS and Linux

2022-10-09 00:28 UTC, merged