Disabling Defender on Win 22H2 Maschines
hak5/usbrubberducky-payloads pull request #175
Opened 2022-11-11 13:28 UTC by HackingMark

You can choose between disabling/restoring with and without PS History deletion.
You could also modify the Term Windows Security Center via DEFINE

2022-11-14 07:09 UTC, dallaswinger requested changes

2022-11-14 07:09 UTC, dallaswinger commented on payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
> +          REM Disable Windows Defender
please fix formatting (shouldn't be tabbed in)

2022-11-14 07:09 UTC, dallaswinger commented on payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
> +    FUNCTION DISABLE_WINDOWS_DEFENDER()
please fix formatting (shouldn't be tabbed in)

2022-11-14 07:09 UTC, dallaswinger commented on payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
> +    FUNCTION RESTORE()
please fix formatting (shouldn't be tabbed in)

2022-11-15 07:14 UTC, HackingMark reviewed
Formatting fixed ;)

2022-11-15 07:15 UTC, HackingMark commented on payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
> +          REM Disable Windows Defender
Done

2022-11-15 07:15 UTC, HackingMark commented on payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
> +    FUNCTION DISABLE_WINDOWS_DEFENDER()
Done

2022-11-15 07:15 UTC, HackingMark commented on payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
> +    FUNCTION RESTORE()
Done

2022-11-17 20:37 UTC, merged