Pranh(ex)
hak5/usbrubberducky-payloads pull request #348
Opened 2023-06-14 09:41 UTC by aleff-github

2023-10-18 08:20 UTC, aleff-github commented
> please remove any of the intermediate build artifacts that are not 100% required
> 
> a brief description of what the prank is supposed to actually do on the target system might also be useful (atleast one that is less buried)

Solved > 39ae8691ff19069ca582a81d86b61854141a35df

2024-08-26 01:56 UTC, hak5peaks requested changes

2025-02-10 04:42 UTC, dallaswinger commented
@hak5peaks

2025-02-11 18:00 UTC, aleff-github commented on payloads/library/prank/Pranh(ex)/assets/hexfile.txt
I had forgotten to remove it, done!

2025-02-11 20:15 UTC, hak5peaks requested changes

2025-02-16 22:00 UTC, merged