Defend Yourself From CVE-2023-23397
hak5/usbrubberducky-payloads pull request #354
Opened 2023-06-27 07:51 UTC by aleff-github

2023-10-17 19:28 UTC, dallaswinger commented
credentials seems to be the wrong category/directory for this 

probably more appropriately incident-response or general

2023-10-18 09:17 UTC, aleff-github commented
> credentials seems to be the wrong category/directory for this
> 
> probably more appropriately incident-response or general

I tried some time ago to discuss it in discord chat as well, and I think actually moving it to incident-response is the best thing

Solved > 92defad8d799b192a6ba1a537bb92f613b0eb774

2024-07-08 18:16 UTC, hak5peaks requested changes

2024-07-08 18:16 UTC, hak5peaks commented on payloads/library/incident_response/Defend_yourself_from_CVE-2023-23397/payload.txt
> +DELAY 1000
Your target machine seems to be Windows. Please consider using `EXTENSION PASSIVE_WINDOWS_DETECT` this will remove the need for a long starting delay and prevent people from running this on the wrong OS

2024-07-09 05:36 UTC, aleff-github commented on payloads/library/incident_response/Defend_yourself_from_CVE-2023-23397/payload.txt
> +DELAY 1000
fair point 👍

2024-07-09 13:45 UTC, merged