Exfiltrate Windows Product Key
hak5/usbrubberducky-payloads pull request #400
Opened 2023-11-03 11:44 UTC by aleff-github

Through this payload, you can export the key information related to the Windows Product Key, knowing its type and the key itself, using a Discord Webhook.

2024-01-03 21:25 UTC, dallaswinger commented
I'll be honest I think if this were to be used for "legit purposes" exfiltrating to the ducky storage would make a lot more sense (and is less likely to be misused) Imagining being in IT and decommissioning a PC that will be replaced and trying to retrieve the key for transfer, setting up a discord server and webhook seems like a lot of arbitrary extra work;

That being said, this would be a good opportunity to have both exfiltration methods in the payload and use `IF_DEFINED_TRUE` to allow the user to configure which method theyd prefer 

just my 2c; open to rebuttal

2024-01-04 11:48 UTC, aleff-github commented
> That being said, this would be a good opportunity to have both exfiltration methods in the payload and use `IF_DEFINED_TRUE` to allow the user to configure which method theyd prefer

This is a very good idea indeed, I had not considered the possibility of using both methods.
I plan to modify this payload appropriately based on your advice as soon as I can.

2024-08-20 06:21 UTC, hak5peaks requested changes

2024-08-20 06:21 UTC, hak5peaks commented on payloads/library/exfiltration/Exfiltrate_Windows_Product_Key/payload.txt
> +DEFINE #USB-RUBBER-DUCKY-STORAGE TRUE
Please go through and remove `-` from Defines, Functions and Function calls.

2024-08-20 21:03 UTC, hak5peaks requested changes

2024-08-20 21:03 UTC, hak5peaks commented on payloads/library/exfiltration/Exfiltrate_Windows_Product_Key/payload.txt
> +STRING powershell
You would use `STRINGLN` in place of `STRING` `ENTER`

2024-08-21 05:34 UTC, aleff-github commented on payloads/library/exfiltration/Exfiltrate_Windows_Product_Key/payload.txt
> +STRING powershell
yes I agree but some time ago I had used the STRINGLN command in the execution pane and I don't know why it didn't work (I think it was a bug due for some strange reason from my computer) and since then I have always used STRING and ENTER in this step.
However, I recognize that it is preferable to use STRINGLN so I will make the change anyway so that others can have a cleaner program.

2024-08-21 05:36 UTC, aleff-github commented on payloads/library/exfiltration/Exfiltrate_Windows_Product_Key/payload.txt
> +        $m=(Get-Volume -FileSystemLabel 'DUCK').DriveLetter;
I am convinced that I had made this change in the past 😅, I have no idea why I cannot find it now.
I am probably getting confused with another payload lol....

Anyway, yes, I completely agree with your suggestion, thanks for pointing it out to me.

2024-08-21 22:42 UTC, merged