Extension: SAVE FILES IN RUBBER DUCKY STORAGE
hak5/usbrubberducky-payloads pull request #427
Opened 2024-01-04 16:04 UTC by aleff-github

Creation of the extension "SAVE FILES IN RUBBER DUCKY STORAGE" based on the old similar proposal "Send Files Through Dropbox - Windows"[1]

[1] https://github.com/hak5/usbrubberducky-payloads/pull/399

2024-01-08 07:33 UTC, dallaswinger commented
please remove spaces from folder name

2024-05-30 20:53 UTC, hak5peaks requested changes

2024-05-30 20:53 UTC, hak5peaks commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +    STRINGLN $m=(Get-Volume -FileSystemLabel 'DUCK').DriveLetter;
I would suggest using a DEFINE for those who may not be using the default drive label of "DUCKY"

2024-05-30 20:53 UTC, hak5peaks commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +
Please remove random line spacing.

2024-05-30 20:53 UTC, hak5peaks commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +
Please remove random line spacing.

2024-05-30 20:53 UTC, hak5peaks commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +EXTENSION SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows
Please dont mix `_` and `-` and make Windows all caps.

2024-06-01 07:50 UTC, aleff-github commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +EXTENSION SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows
I am working on the corrections but curiosity prompts me to ask if I should make this change, in this particular case, because it is considered a syntax error or if by a writing convention.

2024-06-01 08:28 UTC, aleff-github commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +
I understood the advice and tried to make the code as readable as possible. If there are any further inconsistencies I would kindly ask you to point them out to me so I can take action.
Ty ^^

2024-06-01 08:28 UTC, aleff-github commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +EXTENSION SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows
> @hak5peaks
> 
> > Please dont mix `_` and `-` and make Windows all caps.
> 
> I am working on the corrections but curiosity prompts me to ask if I should make this change, in this particular case, because it is considered a syntax error or if by a writing convention.

I tried to ask on Discord and was answered. I think I made all the changes reported in the last commit.

2024-06-01 08:32 UTC, aleff-github commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE-Windows.txt
> +    STRINGLN $m=(Get-Volume -FileSystemLabel 'DUCK').DriveLetter;
did in the last commit, ty

2024-08-20 06:13 UTC, hak5peaks requested changes

2024-08-20 06:13 UTC, hak5peaks commented on payloads/extensions/community/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE/SAVE_FILES_IN_RUBBER_DUCKY_STORAGE_WINDOWS.txt
> +    DEFINE #DRIVER-LABEL DUCK
Please go through and remove `-` from your defines, functions and function calls as they will create a compiling error.

2024-08-20 21:04 UTC, merged