Create payload.txt
hak5/usbrubberducky-payloads pull request #436
Opened 2024-02-03 05:31 UTC by mavisinator30001

2024-05-22 02:01 UTC, hak5peaks requested changes

2024-09-16 13:48 UTC, mavisinator30001 commented on payloads/library/prank/payload.txt
> +HOLD DOWN
Sorry it took me so long to respond to these, I will work on those improvements! Thank you! I also used my gaming pc to test this payload, but I also realize that it is faster than a majority of other computers, so all of this feedback helps a ton! Thank you!

2024-09-16 14:07 UTC, mavisinator30001 commented on payloads/library/prank/payload.txt
> +TAB
I didn't read thoroughly through the Duckyscript documentation, just not how I retain information.... ADHD. That is very good to know, thank you.

2024-09-16 15:08 UTC, mavisinator30001 commented on payloads/library/prank/payload.txt
> +REM Title: Resolution Prank
Understood.

2024-09-16 15:22 UTC, mavisinator30001 commented on payloads/library/prank/payload.txt
> +DELAY 2000
What would be the difference between that and saying, for instance, `IF ($_OS == WINDOWS)` and just having the code in the IF statement ?

2024-09-16 15:33 UTC, mavisinator30001 commented on payloads/library/prank/payload.txt
> +DELAY 2000
When I use the `IF ($_OS == WINDOWS)` statement and test my payload on my personal laptop, which runs Windows 11, it does not sense that it is a Windows OS and just skips the entire statement

2024-09-18 14:07 UTC, mavisinator30001 commented on payloads/library/prank/payload.txt
> +DELAY 2000
For some reason I could not get it to sense Windows from my laptop, so I will just provide a disclaimer that it only works on Windows systems.

2024-09-18 14:26 UTC, closed without merging