Rename Everything Similarly
hak5/usbrubberducky-payloads pull request #482
Opened 2024-09-18 17:23 UTC by aleff-github

This script, titled **Rename Everything Similarly**, is written in **DuckyScript 3.0** and designed to rename files and directories recursively on **Windows** or **GNU/Linux** systems, depending on the target environment. The script renames directories and files within a specified directory, giving them sequential and similar names.

Specifically, the ability to add a blank space to the end of the name is used. On Windows systems, if file extension viewing is not enabled the names will look identical to the human eye, while on GNU/Linux systems the difference may be more easily noticed.

---

![No extensions](https://github.com/aleff-github/Deposito/blob/main/Rename_Everything_Similarly/1.png?raw=true)

> How does renaming files using spaces without seeing the extension appear on windows. - To the human eye they look identical.

---

![With extensions](https://github.com/aleff-github/Deposito/blob/main/Rename_Everything_Similarly/2.png?raw=true)

> What it looks like instead if you turn on the extension view.

2024-09-20 06:11 UTC, hak5peaks requested changes

2024-09-20 06:11 UTC, hak5peaks commented on payloads/library/prank/Rename_Everything_Similarly/README.md
I would rename this payload and include prank in the title. With its current title it could be misinterpreted as a utility. 

`Same File Name Prank` or something similar

2024-09-21 07:43 UTC, aleff-github commented on payloads/library/prank/Rename_Everything_Similarly/payload.txt
> +DEFINE #TRUE_IF_THE_TARGET_IS_WINDOWS_ELSE_FALSE TRUE
i moved to this

```
REM Set TARGET_WINDOWS to TRUE if the script will run on a Windows system.
REM Set TARGET_LINUX to TRUE if the script will run on a GNU/Linux system.
DEFINE #TARGET_WINDOWS TRUE
DEFINE #TARGET_GNU_LINUX FALSE

REM %%%%% PAYLOAD-SECTION %%%%%

IF (( #TARGET_WINDOWS == TRUE) && (#TARGET_GNU_LINUX == FALSE)) THEN
REM %%%%% WINDOWS CODE %%%%%
[...]
ELSE IF (( #TARGET_WINDOWS == FALSE) && (#TARGET_GNU_LINUX == TRUE)) THEN
REM %%%%% GNU/LINUX CODE %%%%%
[...]
END_IF
```

2024-09-24 19:48 UTC, hak5peaks commented on payloads/library/prank/Rename_Everything_Similarly/payload.txt
> +DEFINE #TRUE_IF_THE_TARGET_IS_WINDOWS_ELSE_FALSE TRUE
Awesome! Thank you

2024-09-24 19:48 UTC, merged