Disable WiFi - MacOS
hak5/usbrubberducky-payloads pull request #492
Opened 2024-10-30 16:13 UTC by brunoooost

Implementing the Disable WiFi - MacOS payload to the execution category on Hak5 - USB Rubber Ducky.

- **Disable WiFi - MacOS:** This payload is designed to turn off the Wi-Fi on a MacOS system.

2024-10-30 19:20 UTC, hak5peaks requested changes

2024-10-30 19:20 UTC, hak5peaks commented on payloads/library/execution/Disable WiFi - MacOS/payload.txt
Please rename your directory and remove any spaces and replace them with `-` or `_` 


>Naming Conventions
Please give your payload a unique, descriptive and appropriate name. Do not use spaces in payload, directory or file names. Each payload should be submit into its own directory, with - or _ used in place of spaces, to one of the categories such as exfiltration, phishing, remote_access or recon. Do not create your own category.

2024-10-30 19:25 UTC, brunoooost commented
done

2024-10-30 19:32 UTC, hak5peaks commented
You changed the PR name. 

The payload directory name needs to be changed, currently its `Disable WiFi - MacOS` 

it needs to be `Disable_WiFi-MacOS` or `Disable-WiFi-MacOS` the directory name cannot contain spaces.

2024-10-31 08:39 UTC, brunoooost commented
Now, yes

2024-10-31 10:54 UTC, merged