Adding RickRoll-Contact-iOS
hak5/usbrubberducky-payloads pull request #498
Opened 2024-11-04 13:59 UTC by brunoooost

Adding RickRoll-Contact-iOS, a payload for iOS.
- This payload is a prank script designed to create a contact named "Ricky Astley".

2024-11-05 20:05 UTC, hak5peaks requested changes

2024-11-05 20:05 UTC, hak5peaks commented on payloads/library/prank/RickRoll-Contact-iOS/README.md
I understand how this is a prank, however I would move it to the `/mobile/iOS` directory since its better fitting there. You can include prank within the title or description.

2024-11-05 20:49 UTC, brunoooost commented on payloads/library/prank/RickRoll-Contact-iOS/README.md
so, do you want me to change the category to the mobile/iOS ?

2024-11-06 10:50 UTC, brunoooost commented
done

2024-11-07 10:20 UTC, merged