Create Chromebook-Auto-Subscribe
hak5/usbrubberducky-payloads pull request #507
Opened 2024-12-29 03:02 UTC by Ninegd4

My payload works for chromebooks, (Chromebook tested)

-It auto subscribes to the YouTube account linked
-Others can use it by going to https://payloadstudio.hak5.org/community/ and putting it in there then clicking Generate payload, then clicking download to download the inject.bin file
-The only configuration needed is for whoever is using it to change the part that says <your-youtubeaccount-link.com> with the actual YouTube account link
-Have fun with it

2024-12-29 03:04 UTC, Ninegd4 commented
Ill do anything needed to configure it to get on there

2024-12-29 19:10 UTC, hak5peaks requested changes

2024-12-29 19:10 UTC, hak5peaks commented on payloads/library/prank/Chromebook-Auto-Subscribe
> +TAB
For instances where you are repeating a certain action continuously you can use `REPEAT` . 
```
REPEAT 14 TAB
``` 
This cleans up the payload and make it more readable. while keeping the same functionality.

2024-12-30 12:18 UTC, Ninegd4 commented on payloads/library/prank/Chromebook-Auto-Subscribe
> +STRING chrome
Would I type: (STRINGLN chrome) ?

2024-12-30 12:34 UTC, Ninegd4 commented on payloads/library/prank/Chromebook-Auto-Subscribe
Would I go back into my copy of it and do that whole process again? I'm confused on how to do the changes here on this specific one you wrote

2024-12-30 12:46 UTC, Ninegd4 commented on payloads/library/prank/Chromebook-Auto-Subscribe
I have it up to here: /payloads/library/execution/Chromebook-Auto-Subscribe and when you click on the Chromebook-Auto-Subscribe file under execution, it opens up the script, I have absolutely no clue on how to make it a payload.txt file under Chromebook-Auto-Subscribe

2024-12-30 12:55 UTC, Ninegd4 commented on payloads/library/prank/Chromebook-Auto-Subscribe
Wait, Nevermind. I Just reuploaded it again, I accidentally just reposted the code updated but Im re commiting this one with payload.txt in it as well as ReadMe.txt. Im sorry for the confusion

2024-12-30 12:58 UTC, Ninegd4 commented on payloads/library/prank/Chromebook-Auto-Subscribe
Nevermind again, would you mind giving me a tutorial? I have a file in my files named Chromebook-Auto-Subscribe with the paylaod.txt and ReadMe.txt in it but I have no idea how to upload this.

2024-12-30 15:45 UTC, hak5peaks commented on payloads/library/prank/Chromebook-Auto-Subscribe
> +STRING chrome
Yes, Instead of doing 
```
STRING chrome
ENTER
```
You can simply do 
`STRINGLN chrome` 
This will achieve the same functionality

2024-12-30 15:54 UTC, hak5peaks requested changes

2024-12-30 15:54 UTC, hak5peaks commented on payloads/library/execution/Chromebook-Auto-Subscribe
You moved it to the correct payload category directory, however its still missing the payload directory itself. 

Try putting a `/` after `Chromebook-Auto-Subscribe` then payload.txt when renaming the file. 

`Chromebook-Auto-Subscribe/payload.txt`

2024-12-30 15:54 UTC, hak5peaks commented on payloads/library/execution/Chromebook-Auto-Subscribe
> +DEFINE #YTLINK example.com
I would move the `DEFINE` to the top of the payload, under under your `REM` So users can easily see and configure it.

2025-01-02 01:26 UTC, Ninegd4 commented
I'm really sorry but I've been incredibly busy so it'd be nice if someone else could mess with the script to make it better. Once again I apologize, I love the Hak5 community and I love the products you make but I've been a little burned out lately cause I have a lot of stuff to do.

2025-01-02 13:35 UTC, hak5peaks commented
Its completely ok! Thank you for the kind words, we highly appreciate your effort and contribution. We will keep the PR open for if you want to re-visit and make changes in the future.

2025-08-31 04:01 UTC, Ninegd4 commented on payloads/library/prank/Chromebook-Auto-Subscribe
> +TAB
Im back in business and will be fixing this up shortly

2025-08-31 04:15 UTC, Ninegd4 commented
I have a new code all fixed up, do I start a new pull request?

2025-08-31 04:20 UTC, Ninegd4 commented
[README.txt](https://github.com/user-attachments/files/22062672/README.txt)
[payload.txt](https://github.com/user-attachments/files/22062674/payload.txt)

2025-08-31 21:10 UTC, hak5peaks commented
You can modify the payload and readme content on your own branch and then update your PR to include the changes.

2025-09-01 03:36 UTC, closed without merging